package cn.cld.dao;

import cn.cld.pojo.shopOrderDetail;
import cn.cld.pojo.shopOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface shopOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int countByExample(shopOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int deleteByExample(shopOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int insert(shopOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int insertSelective(shopOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    List<shopOrderDetail> selectByExampleWithRowbounds(shopOrderDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    List<shopOrderDetail> selectByExample(shopOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    shopOrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") shopOrderDetail record, @Param("example") shopOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int updateByExample(@Param("record") shopOrderDetail record, @Param("example") shopOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int updateByPrimaryKeySelective(shopOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_detail
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    int updateByPrimaryKey(shopOrderDetail record);
}