package cn.cld.dao;

import cn.cld.pojo.shopOrder;
import cn.cld.pojo.shopOrderExample;
import cn.cld.pojo.shopOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface shopOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int countByExample(shopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int deleteByExample(shopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int deleteByPrimaryKey(shopOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int insert(shopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int insertSelective(shopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    List<shopOrder> selectByExampleWithRowbounds(shopOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    List<shopOrder> selectByExample(shopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    shopOrder selectByPrimaryKey(shopOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") shopOrder record, @Param("example") shopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int updateByExample(@Param("record") shopOrder record, @Param("example") shopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int updateByPrimaryKeySelective(shopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    int updateByPrimaryKey(shopOrder record);
}