package cn.cld.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class shopOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.id
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.shop_order_no
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private String shopOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.product_id
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.price
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.count
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.amount
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.creat_date
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private Date creatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order_detail.update_date
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.id
     *
     * @return the value of shop_order_detail.id
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.id
     *
     * @param id the value for shop_order_detail.id
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.shop_order_no
     *
     * @return the value of shop_order_detail.shop_order_no
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public String getShopOrderNo() {
        return shopOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.shop_order_no
     *
     * @param shopOrderNo the value for shop_order_detail.shop_order_no
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setShopOrderNo(String shopOrderNo) {
        this.shopOrderNo = shopOrderNo == null ? null : shopOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.product_id
     *
     * @return the value of shop_order_detail.product_id
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.product_id
     *
     * @param productId the value for shop_order_detail.product_id
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.price
     *
     * @return the value of shop_order_detail.price
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.price
     *
     * @param price the value for shop_order_detail.price
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.count
     *
     * @return the value of shop_order_detail.count
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.count
     *
     * @param count the value for shop_order_detail.count
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.amount
     *
     * @return the value of shop_order_detail.amount
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.amount
     *
     * @param amount the value for shop_order_detail.amount
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.creat_date
     *
     * @return the value of shop_order_detail.creat_date
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.creat_date
     *
     * @param creatDate the value for shop_order_detail.creat_date
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order_detail.update_date
     *
     * @return the value of shop_order_detail.update_date
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order_detail.update_date
     *
     * @param updateDate the value for shop_order_detail.update_date
     *
     * @mbggenerated Tue Apr 16 17:25:44 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}