package cn.cld.pojo;

public class shopOrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.id
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.sell_order_no
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    private String sellOrderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.id
     *
     * @return the value of shop_order.id
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.id
     *
     * @param id the value for shop_order.id
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.sell_order_no
     *
     * @return the value of shop_order.sell_order_no
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public String getSellOrderNo() {
        return sellOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.sell_order_no
     *
     * @param sellOrderNo the value for shop_order.sell_order_no
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public void setSellOrderNo(String sellOrderNo) {
        this.sellOrderNo = sellOrderNo == null ? null : sellOrderNo.trim();
    }
}