package cn.cld.pojo;

import java.util.Date;

public class shopOrder extends shopOrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.shop_id
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.order_amout
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    private Long orderAmout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.create_date
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_order.update_date
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.shop_id
     *
     * @return the value of shop_order.shop_id
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.shop_id
     *
     * @param shopId the value for shop_order.shop_id
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.order_amout
     *
     * @return the value of shop_order.order_amout
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public Long getOrderAmout() {
        return orderAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.order_amout
     *
     * @param orderAmout the value for shop_order.order_amout
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public void setOrderAmout(Long orderAmout) {
        this.orderAmout = orderAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.create_date
     *
     * @return the value of shop_order.create_date
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.create_date
     *
     * @param createDate the value for shop_order.create_date
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_order.update_date
     *
     * @return the value of shop_order.update_date
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_order.update_date
     *
     * @param updateDate the value for shop_order.update_date
     *
     * @mbggenerated Tue Apr 16 17:23:49 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}